### ISSUE TITLE
挺好用的！但是想提出两个优化点！

### ISSUE THREAD

**Issue by JasonkayZK** [JarenChow/JMind#1]
1. 能否支持svg导出，目前使用 Ctrl + S 保存的时候，保存的是一个txt文件；但是有时候我完全画完思维导图，是想要保存为图片的；

2. 目前都是需要按键进行操作的，能否添加几个Button，可以在平板等移动端进行操作；

最后，非常感谢大佬啦！♥

**Comment by JarenChow** [comment]
目前保存为txt的目的是Ctrl+o能打开文件并恢复导图呢，保存为图片的功能和移动端适配暂时木有时间做呀，以后可能会做

**Comment by JasonkayZK** [comment]
> 目前保存为txt的目的是Ctrl+o能打开文件并恢复导图呢，保存为图片的功能和移动端适配暂时木有时间做呀，以后可能会做
> […](#)
> 在 2021年3月30日，09:51，Jasonkay ***@***.***> 写道： ﻿ 能否支持svg导出，目前使用 Ctrl + S 保存的时候，保存的是一个txt文件；但是有时候我完全画完思维导图，是想要保存为图片的； 目前都是需要按键进行操作的，能否添加几个Button，可以在平板等移动端进行操作； 最后，非常感谢大佬啦！♥ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，我体验了保存为txt和恢复的功能，挺轻量级的；

保存为图片和移动端适配可以作为feature后续加入呗，蟹蟹辣！

**Comment by JarenChow** [comment]
感谢你的喜欢～我从一开始做这个的时候对它的定位就是极速、轻量和高还原度，一些额外的功能可能后续只在得空时才会继续开发，因为毕竟人家商业软件早已经把所有功能都几乎做全了，我再把所有功能都造一遍轮子似乎说不过去哈哈

**Comment by JasonkayZK** [comment]
好滴鸭，没问题的！😄

**Comment by JasonkayZK** [comment]
> 感谢你的喜欢～我从一开始做这个的时候对它的定位就是极速、轻量和高还原度，一些额外的功能可能后续只在得空时才会继续开发，因为毕竟人家商业软件早已经把所有功能都几乎做全了，我再把所有功能都造一遍轮子似乎说不过去哈哈
> […](#)
> 在 2021年3月30日，10:01，Jasonkay ***@***.***> 写道： ﻿ 目前保存为txt的目的是Ctrl+o能打开文件并恢复导图呢，保存为图片的功能和移动端适配暂时木有时间做呀，以后可能会做 … 在 2021年3月30日，09:51，Jasonkay @.***> 写道： ﻿ 能否支持svg导出，目前使用 Ctrl + S 保存的时候，保存的是一个txt文件；但是有时候我完全画完思维导图，是想要保存为图片的； 目前都是需要按键进行操作的，能否添加几个Button，可以在平板等移动端进行操作； 最后，非常感谢大佬啦！♥ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 是的，我体验了保存为txt和恢复的功能，挺轻量级的； 保存为图片和移动端适配可以作为feature后续加入呗，蟹蟹辣！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

最近比较忙，今天试了一下你发的那个保存的。在大图片、小图片，中文下都没问题。
大佬666；
感觉代码可以合并到主代码，让大家都用呗~

**Comment by JarenChow** [comment]
我最近又修复了一下存为图片的逻辑，适配了高清屏的问题，保存为了占用更低的jpeg格式，到时候我再整理一下发出来吧。另外，不用老叫我大佬啦，互相学习哈～
