### ISSUE TITLE
希望出个docker版的

### ISSUE THREAD

**Issue by valuex** [JarenChow/JMind#2]
希望出个docker版本的，方便自行部署，谢谢。

**Comment by JarenChow** [comment]
我不知道咋弄呀能不能教我~目前只需有一个带宽高的 dom 容器 + xmind.js 就可以运行了呀

**Comment by JasonkayZK** [comment]
> 希望出个docker版本的，方便自行部署，谢谢。

总共就一个html文件，就没必要用docker了吧…，自己搞个nginx反代不完事了。

**Comment by valuex** [comment]
@JasonkayZK  谢谢提示, 已经在群晖上部署好了, 并在此项目下增加了一个简易教程.
希望 @JarenChow  可以合入,谢谢.
