### ISSUE TITLE
我把背景透明了，会出现残影

### ISSUE THREAD

**Issue by itancc** [JarenChow/JMind#6]
![image](https://user-images.githubusercontent.com/46319251/125224213-bec43680-e2ff-11eb-9f77-acc5f4f1b081.png)
会出现上面图片的情况。

**Comment by JarenChow** [comment]
1156 行 `this.background.fill();` 替换成 `this.$clear();` 即可透明背景

**Comment by itancc** [comment]
大佬，非常感谢！

**Comment by JarenChow** [comment]
没事，举手之劳
